### ISSUE TITLE
Switch to S3 instead of archiving to a server

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-archive#10]
It seems somewhat unnecessary to have an entire server that is just used as a hard disk.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consider S3 Glacier instead of kingfisher-archive server](https://trello.com/c/xGkc11Pf/91-consider-s3-glacier-instead-of-kingfisher-archive-server)

**Comment by ghost** [comment]
I think(??) @robredpath looked at a price analysis on this at the time, so assigning to him for further discussion.

**Comment by robredpath** [comment]
@jpmckinney 

Definitely a good question to ask at this point. We bought the archive server because it was a relatively low-cost way of providing more resources than we would ever use, in a very quick and easy-to-use way. It also provided a very straightforward interface, instead of having to learn about and use APIs and security considerations that we hadn't previously had to think about. At the time, the analysis of cost per month vs the cost of our time to properly investigate alternatives landed on the side of the cost per month. 

The archive server was also a useful second server during the development of kingfisher-views, as it allowed us to carry out the very intensive processing required by the earlier versions while not stopping the incoming stream of data from scrapes. 

Moving to an S3-based system would be relatively simple, and would reduce the monthly cost. We currently use about 160GB of space, which would cost far less than the server. It'll increase over time, but at the current rate, it'll be years before it's the same cost. We'd want to spend a bit of time making sure that we properly understood the 'AWS way', especially around interaction with security, but with the AWS cli, it won't be a difficult operation. We don't use the archive all that much, in practice, so Glacier would be fine. With the volume of data, regular S3 or S3 Infrequent Access would be perfectly affordable as well. 

There have been conversations about carrying out more processing as part of the Data Quality Tools work. In that case, we might want to move kingfisher-views to the server that we currently have for archiving, so that there's more processing power available for processing. The same might well apply to the informal analysis use of the main Kingfisher server - we might want to move that function to the archive server as well, as we can set up users, load custom data sets and carry out analysis there at will.

**Comment by jpmckinney** [comment]
It sounds like we should use S3 (whether Standard, Infrequent Access or Glacier) for the purpose of archiving data. Personally I think Glacier is right for now, as I'm not sure we've ever accessed archived data, and if we have, I don't think the retrieval time would've been an issue.

It doesn't look like we have a well-established demand/need for a separate server for Views or manual analysis at this time. We can always spin up a server easily once we have a need.

**Comment by jpmckinney** [comment]
Copying progress from Trello:

* James emailed code@opendataservices.coop with account information, and sent the password and secret access key to Rob via WhatsApp. The account has full access to S3 and Glacier.
* For context, the current (2019-09-19) 200GB of data would cost $4.60/mo on the top tier of storage.
* boto3 (recommended by AWS) supports S3 and Glacier.

Need to implement a CLI tool to:

* backup files on a regular basis
* restore files on demand

**Comment by jpmckinney** [comment]
We can also delete [this page](https://ocdskingfisher.readthedocs.io/en/latest/archive.html) or move the content to the deploy repo, as it's of no interest to non-OCP/helpdesk users.

**Comment by jpmckinney** [comment]
Digital Ocean Spaces has an S3-compatible API and is more affordable if we expect some data transfer out. https://www.digitalocean.com/pricing/#Storage

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Archive to S3 and decommission server](https://trello.com/c/LSzAt3nw/234-archive-to-s3-and-decommission-server)

**Comment by jpmckinney** [comment]
Adding link to planning doc: https://docs.google.com/document/d/13tReafVVr6SKEXi833ajlXXIlPTh0TtjrMK5akP7meA/edit
