### ISSUE TITLE
Should we use xz format?

### ISSUE THREAD

**Issue by ghost** [open-contracting/kingfisher-archive#7]
I just came across this recently :-) http://lzip.nongnu.org/xz_inadequate.html

**Comment by ghost** [comment]
Discussed briefly in call. We'll leave this - we have faith in Ubuntu LTS to keep us right.

**Comment by jpmckinney** [comment]
Noting in 9382912088727df47c8205082ab187dfe4e01b9f and 421cfd3d31b2ff58a4e9e93b5d34a6275b1bc05f I switched from xz to 7z to lz4, which prioritizes speed (for both compression and decompression) over size (for which xz is best).

This FB Engineering post (https://engineering.fb.com/2018/12/19/core-data/zstandard/) explains the use cases for each algorithm, along with [zstd](https://facebook.github.io/zstd/) (created at Facebook by Yann Collet, who previously created lz4).


When archiving data: Compression time is relevant during development, testing and manual operation, but not during automatic operation (which will be most of the time). Storage size is relevant in terms of cost, but we presently estimate such costs to be quite low. Transfer time is not particularly relevant at any time.

When restoring data (which occurs rarely): Decompression time and transfer time are relevant, and storage size affects transfer time. If we start restoring data frequently, we might find a particular compression level of zstd better meets our needs by yielding smaller storage sizes and thus transfer times, while having similar decompression times.

Since we're presently still doing a lot of development, testing and manual operation, we'll continue to prioritize compression time, so using lz4.

----

Both lz4 and zstd can accept a dictionary as input, but as described in the FB post, it can get quite complicated to train the dictionary, so I don't think we'll ever go that far.
